"""Installing, rendering, and removing choom's assistant discovery file.

The discovery file is a short, choom-owned pointer written into an assistant's own
user-scope profile directory -- outside the workspace -- so that assistant can find the
workspace and its `AGENTS.md` no matter where it is started (spec 013-assistant-
discovery-file). This is the only module in choom that writes anything outside the
workspace.

`profile_root()` is the only place in the whole codebase that resolves the user's own
profile directory. Every other function here starts from it rather than calling
`Path.home()` directly, so tests can redirect the entire module into a `tmp_path` by
monkeypatching this one function (research R13) -- see `tests/conftest.py`'s autouse
fixture, which does exactly that for every test, so no test can write into a developer's
real `~/.claude` or `~/.copilot`.
"""

from __future__ import annotations

from pathlib import Path

from choom.core.models import AssistantProfile, Workspace

#: The fixed, greppable string every discovery file carries (FR-005), naming choom and
#: the command that rewrites it. Doing double duty (contracts/discovery-file.md, R11):
#: it tells a user who finds the file that hand-editing it is pointless, and it is the
#: precondition `remove_discovery_files` checks before deleting anything -- a file at
#: one of our paths without this string is not ours to remove.
MARKER = (
    "<!-- Generated by choom (`choom config assistant`). "
    "Rewritten on every run; edits are lost. -->"
)

#: What choom is, in one line -- reused for both the rendered body and, for the Claude
#: skill, the frontmatter `description` an assistant matches against to decide whether
#: the skill is relevant (research R1), so it has to carry the same fact either way.
_WHAT_CHOOM_IS = (
    "choom is a plain-Markdown notes and meeting tool; this workspace holds the "
    "user's notes and meetings."
)


def profile_root() -> Path:
    """The user's own profile directory: `Path.home()`, which resolves
    `%USERPROFILE%` on Windows and `$HOME` elsewhere (research R3).

    The only function in this module that calls `Path.home()`. Every other path this
    module computes is built from this one's return value, so redirecting it -- as the
    test suite's autouse fixture does -- redirects everything (research R13).
    """
    return Path.home()


def discovery_path(profile: AssistantProfile) -> Path | None:
    """The absolute path of `profile`'s discovery file, or None when it has no
    user-scope location (FR-017)."""
    if profile.discovery_relpath is None:
        return None
    return profile_root() / profile.discovery_relpath


def render_discovery_file(workspace: Workspace, profile: AssistantProfile) -> str:
    """Render the discovery file's full content for `profile`, pointing at `workspace`
    (contracts/discovery-file.md). Deterministic: rendering the same workspace and
    profile twice produces byte-identical output -- no timestamp, no version string --
    so a re-run with nothing changed writes no real diff (FR-006).

    Restates nothing `AGENTS.md` itself says (FR-003): no layout, no frontmatter
    schema, no task line format, no link syntax, no command list, no exit codes. What
    cannot be inferred by following the pointer is only that choom exists, where the
    workspace is, and that `AGENTS.md` holds the rest -- so that is all this carries.

    Differs only in the wrapper each assistant expects (research R10): YAML frontmatter
    naming the Claude Code skill, or a plain heading for the Copilot CLI instructions
    file. The body is otherwise identical, and the workspace's absolute path sits alone
    on its own line, unquoted, so spaces and non-ASCII characters need no escaping
    rules the reader has to know (FR-018).
    """
    body = (
        f"{_WHAT_CHOOM_IS}\n"
        "\n"
        "The user's choom workspace is at:\n"
        "\n"
        f"{workspace.root}\n"
        "\n"
        "Read `AGENTS.md` in that directory before creating or changing anything in "
        "it. It documents the commands, the layout, and the file format this tool "
        "expects.\n"
        "\n"
        f"{MARKER}\n"
    )
    if profile.name == "claude":
        frontmatter = f"---\nname: choom\ndescription: {_WHAT_CHOOM_IS}\n---\n\n"
        return f"{frontmatter}# choom\n\n{body}"
    return f"# choom\n\n{body}"
