"""Installing, rendering, and removing choom's assistant discovery file.

The discovery file is a short, choom-owned pointer written into an assistant's own
user-scope profile directory -- outside the workspace -- so that assistant can find the
workspace and its `AGENTS.md` no matter where it is started (spec 013-assistant-
discovery-file). This is the only module in choom that writes anything outside the
workspace.

`profile_root()` is the only place in the whole codebase that resolves the user's own
profile directory. Every other function here starts from it rather than calling
`Path.home()` directly, so tests can redirect the entire module into a `tmp_path` by
monkeypatching this one function (research R13) -- see `tests/conftest.py`'s autouse
fixture, which does exactly that for every test, so no test can write into a developer's
real `~/.claude` or `~/.copilot`.
"""

from __future__ import annotations

from pathlib import Path

from choom.core.assistants import PROFILES
from choom.core.atomic_write import write_text_atomic
from choom.core.config import get_launch_offer_made
from choom.core.models import AssistantProfile, ResolvedAssistant, Workspace

#: The fixed, greppable string every discovery file carries (FR-005), naming choom and
#: the command that rewrites it. Doing double duty (contracts/discovery-file.md, R11):
#: it tells a user who finds the file that hand-editing it is pointless, and it is the
#: precondition `remove_discovery_files` checks before deleting anything -- a file at
#: one of our paths without this string is not ours to remove.
MARKER = (
    "<!-- Generated by choom (`choom config assistant`). "
    "Rewritten on every run; edits are lost. -->"
)

#: What choom is, in one line, for the rendered body.
_WHAT_CHOOM_IS = (
    "choom is a plain-Markdown notes and meeting tool; this workspace holds the "
    "user's notes and meetings."
)

#: The skill's frontmatter `description` -- what an assistant matches a request
#: against to decide whether to open the skill at all (research R1), which makes it the
#: one string in this file that has to describe *when* choom is relevant rather than
#: what it is. A description that only names the tool gives a request like "write this
#: up" nothing to match on, so the skill is only ever used when the user names it --
#: which is the manual instruction this whole feature exists to remove.
#:
#: Deliberately not `_WHAT_CHOOM_IS`: the body is read once the pointer is already being
#: followed and can be declarative, while this is read cold, against a request, and has
#: to earn the open. Deliberately possessive throughout ("the user's own", "notes of
#: their own") to keep it to personal notes -- "notes" is a common word, and a skill
#: that fires on release notes or notes in a code review is noise the user learns to
#: resent.
#:
#: Restating `AGENTS.md` is still forbidden (FR-003), and this does not: when to reach
#: for choom is not in `AGENTS.md` and cannot be inferred by following the pointer.
#:
#: Kept to a single line: it sits inside the file's 20-line budget (FR-004), and a
#: folded YAML block would spend three or four lines of it on wrapping alone. Contains
#: no ": " or " #" sequence, either of which would end a plain YAML scalar early.
_WHEN_TO_USE_CHOOM = (
    "The user's own meeting notes, daily notes, and task list live in a choom "
    "workspace on this machine. Use it whenever they ask to write up or find a "
    "meeting, capture a note or a thought, add or tick off a task, or refer to notes "
    "of their own -- including implicit requests like write this up, add a follow-up "
    "for that, or what did I decide about the renewal. Says where the workspace is "
    "and where its instructions are."
)


def profile_root() -> Path:
    """The user's own profile directory: `Path.home()`, which resolves
    `%USERPROFILE%` on Windows and `$HOME` elsewhere (research R3).

    The only function in this module that calls `Path.home()`. Every other path this
    module computes is built from this one's return value, so redirecting it -- as the
    test suite's autouse fixture does -- redirects everything (research R13).
    """
    return Path.home()


def discovery_path(profile: AssistantProfile) -> Path | None:
    """The absolute path of `profile`'s discovery file, or None when it has no
    user-scope location (FR-017)."""
    if profile.discovery_relpath is None:
        return None
    return profile_root() / profile.discovery_relpath


def render_discovery_file(workspace: Workspace, profile: AssistantProfile) -> str:
    """Render the discovery file's full content for `profile`, pointing at `workspace`
    (contracts/discovery-file.md). Deterministic: rendering the same workspace and
    profile twice produces byte-identical output -- no timestamp, no version string --
    so a re-run with nothing changed writes no real diff (FR-006).

    Restates nothing `AGENTS.md` itself says (FR-003): no layout, no frontmatter
    schema, no task line format, no link syntax, no command list, no exit codes. What
    cannot be inferred by following the pointer is only that choom exists, where the
    workspace is, and that `AGENTS.md` holds the rest -- so that is all this carries.

    Identical for every supported assistant, because both read the same artifact: a
    `SKILL.md` with `name` and `description` frontmatter, dropped into a user-scope
    skills directory, discovered without registration and loaded only when its
    `description` matches a request (research R1, R2). `profile` is still taken so a
    future assistant wanting a different wrapper has somewhere to put it.

    The workspace's absolute path sits alone on its own line, unquoted, so spaces and
    non-ASCII characters need no escaping rules the reader has to know (FR-018).
    """
    body = (
        f"{_WHAT_CHOOM_IS}\n"
        "\n"
        "The user's choom workspace is at:\n"
        "\n"
        f"{workspace.root}\n"
        "\n"
        "Read `AGENTS.md` in that directory before creating or changing anything in "
        "it. It documents the commands, the layout, and the file format this tool "
        "expects.\n"
        "\n"
        f"{MARKER}\n"
    )
    frontmatter = f"---\nname: choom\ndescription: {_WHEN_TO_USE_CHOOM}\n---\n\n"
    return f"{frontmatter}# choom\n\n{body}"


def installed_discovery_path() -> Path | None:
    """The one choom-owned discovery file currently on disk, across every supported
    assistant's location, or None when none is installed (FR-016).

    "choom-owned" means the marker is present (R11): a same-named file without it is
    not ours to report, so it is skipped rather than returned.
    """
    for profile in PROFILES:
        path = discovery_path(profile)
        if path is None or not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if MARKER in text:
            return path
    return None


def remove_discovery_files(*, keep: AssistantProfile | None = None) -> tuple[list[Path], list[str]]:
    """Remove every choom-owned discovery file except `keep`'s, if given (FR-008,
    FR-009).

    A file is removed only when it exists *and* carries the generated-by marker
    (FR-010, research R11) -- a file at one of our paths without it is somebody else's
    and is left alone, its path returned as a warning rather than deleted on the
    strength of its filename alone.

    Never raises: an unremovable file (e.g. a permissions error) is reported as a
    warning too, so a locked-down profile directory does not turn a `none` set into a
    hard failure -- FR-009 requires it to succeed regardless.

    Returns:
        The paths actually removed, and a warning message for every path that was
        left alone (no marker) or could not be read or removed.
    """
    removed: list[Path] = []
    warnings: list[str] = []
    for profile in PROFILES:
        if keep is not None and profile.name == keep.name:
            continue
        path = discovery_path(profile)
        if path is None or not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            warnings.append(f"could not check {path}: {exc}")
            continue
        if MARKER not in text:
            warnings.append(f"left alone (not choom's): {path}")
            continue
        try:
            path.unlink()
        except OSError as exc:
            warnings.append(f"could not remove {path}: {exc}")
            continue
        removed.append(path)
    return removed, warnings


def install_discovery_file(workspace: Workspace, profile: AssistantProfile) -> Path | None:
    """Install the discovery file for `profile`, pointing at `workspace`, rewriting it
    in full every time (FR-006).

    Writes before removing any choom-owned file a previously configured assistant left
    behind (FR-008, research R11): if the write itself fails, the previous assistant's
    still-working pointer is left in place rather than being deleted ahead of a new one
    that never landed.

    Returns the path written, or None when `profile` has no user-scope location
    (FR-017) -- the caller reports this; the setting itself is unaffected either way
    (FR-013).

    Raises:
        WorkspaceError: the file could not be written -- the profile directory is
            unwritable, or the path is otherwise unusable. The caller is expected to
            catch this and report it without failing the setting write (FR-013,
            FR-014).
    """
    path = discovery_path(profile)
    if path is not None:
        write_text_atomic(path, render_discovery_file(workspace, profile))
    remove_discovery_files(keep=profile)
    return path


def should_offer_discovery(
    workspace: Workspace, resolved: ResolvedAssistant
) -> AssistantProfile | None:
    """Whether to raise the once-only launch offer (US2, FR-022, FR-029), and for which
    profile.

    Pure: reads the workspace's recorded offer and the discovery paths already on disk,
    decides, and returns -- the caller does the asking and, on `Enter`, the installing
    (data-model.md's launch-offer state machine).

    Suppressed when: the offer has already been made for this workspace; the assistant
    is configured as "none"; resolution is ambiguous (two or more assistants installed,
    none configured); no assistant is installed at all; or a discovery file is already
    installed for the assistant that would be offered. Otherwise, the profile choom
    would use -- either detected (exactly one installed, nothing configured) or
    explicitly configured with its file missing (FR-022's "will be used" also covers
    this case) -- is returned.
    """
    if get_launch_offer_made(workspace):
        return None
    if resolved.source in ("none", "ambiguous", "unset"):
        return None
    profile = resolved.profile
    if profile is None:
        return None

    path = discovery_path(profile)
    if path is not None and path.is_file():
        try:
            already_installed = MARKER in path.read_text(encoding="utf-8")
        except OSError:
            already_installed = False
        if already_installed:
            return None

    return profile
